# TCL File Generated by Component Editor 18.1
# Wed May 08 17:28:53 COT 2024
# DO NOT MODIFY


# 
# matrix_multiplier_avalon "matrix_multiplier_avalon" v1.0
# Juan Felipe España Andrade; Jairo Esteban Acevedo Fajardo 2024.05.08.17:28:53
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module matrix_multiplier_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME matrix_multiplier_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Juan Felipe España Andrade; Jairo Esteban Acevedo Fajardo"
set_module_property DISPLAY_NAME matrix_multiplier_avalon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL matrix_multiplier_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file univ_bin_counter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/utilities/univ_bin_counter.vhdl
add_fileset_file singleBarrelShifter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/utilities/barrel_shifter/singleBarrelShifter.vhdl
add_fileset_file barrelShifter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/utilities/barrel_shifter/barrelShifter.vhdl
add_fileset_file singleBarrelShifterLeft.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/utilities/barrelShifterLeft/singleBarrelShifterLeft.vhdl
add_fileset_file barrelShifterLeft.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/utilities/barrelShifterLeft/barrelShifterLeft.vhdl
add_fileset_file type_results.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/utilities/type_results.vhdl
add_fileset_file parallel_adder.vhd VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/mac/parallel_add/parallel_adder.vhd
add_fileset_file multiplier.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/mac/multiplier.vhdl
add_fileset_file sub_adder.vhd VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/mac/sub_add/sub_adder.vhd
add_fileset_file mac.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/mac/mac.vhdl
add_fileset_file memory.vhd VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/memory/memory.vhd
add_fileset_file single_memory.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/memory/single_memory.vhdl
add_fileset_file mac_with_memory.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_with_memory/mac_with_memory.vhdl
add_fileset_file mac_array.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array/mac_array.vhdl
add_fileset_file column_counter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/counters/shifter_counter/column_counter.vhdl
add_fileset_file row_counter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/counters/shifter_counter/row_counter.vhdl
add_fileset_file shifter_counter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/counters/shifter_counter/shifter_counter.vhdl
add_fileset_file operation_counter.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/counters/operation_counter/operation_counter.vhdl
add_fileset_file macs_ena.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/macs_ena/macs_ena.vhdl
add_fileset_file column_decoder.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/memory_decoder/column_decoder/column_decoder.vhdl
add_fileset_file row_decoder.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/memory_decoder/row_decoder/row_decoder.vhdl
add_fileset_file memory_decoder.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/memory_decoder/memory_decoder.vhdl
add_fileset_file mac_array_controller_fsm.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/mac_array_controller_fsm.vhdl
add_fileset_file mac_array_controller.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/mac_array_controller/mac_array_controller.vhdl
add_fileset_file result_decoder.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/result_decoder/result_decoder.vhdl
add_fileset_file matrix_multiplier.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier/matrix_multiplier.vhdl
add_fileset_file float32_to_integer.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/number_converters/float32_to_integer.vhdl
add_fileset_file matrix_multiplier_float.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_float/matrix_multiplier_float.vhdl
add_fileset_file matrix_multiplier_avalon.vhdl VHDL PATH ../hdl/matrix_multiplier_avalon/matrix_multiplier_avalon.vhdl TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter data_size INTEGER 32
set_parameter_property data_size DEFAULT_VALUE 32
set_parameter_property data_size DISPLAY_NAME data_size
set_parameter_property data_size TYPE INTEGER
set_parameter_property data_size UNITS None
set_parameter_property data_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property data_size HDL_PARAMETER true
add_parameter macs_size INTEGER 7 ""
set_parameter_property macs_size DEFAULT_VALUE 7
set_parameter_property macs_size DISPLAY_NAME macs_size
set_parameter_property macs_size TYPE INTEGER
set_parameter_property macs_size UNITS None
set_parameter_property macs_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property macs_size DESCRIPTION ""
set_parameter_property macs_size HDL_PARAMETER true
add_parameter memory_size INTEGER 10
set_parameter_property memory_size DEFAULT_VALUE 10
set_parameter_property memory_size DISPLAY_NAME memory_size
set_parameter_property memory_size TYPE INTEGER
set_parameter_property memory_size UNITS None
set_parameter_property memory_size ALLOWED_RANGES -2147483648:2147483647
set_parameter_property memory_size HDL_PARAMETER true


# 
# display items
# 


# 
# connection point wr_clk_in
# 
add_interface wr_clk_in clock end
set_interface_property wr_clk_in clockRate 0
set_interface_property wr_clk_in ENABLED true
set_interface_property wr_clk_in EXPORT_OF ""
set_interface_property wr_clk_in PORT_NAME_MAP ""
set_interface_property wr_clk_in CMSIS_SVD_VARIABLES ""
set_interface_property wr_clk_in SVD_ADDRESS_GROUP ""

add_interface_port wr_clk_in wr_clk clk Input 1


# 
# connection point rd_clk_in
# 
add_interface rd_clk_in clock end
set_interface_property rd_clk_in clockRate 0
set_interface_property rd_clk_in ENABLED true
set_interface_property rd_clk_in EXPORT_OF ""
set_interface_property rd_clk_in PORT_NAME_MAP ""
set_interface_property rd_clk_in CMSIS_SVD_VARIABLES ""
set_interface_property rd_clk_in SVD_ADDRESS_GROUP ""

add_interface_port rd_clk_in rd_clk clk Input 1


# 
# connection point rst_in
# 
add_interface rst_in reset end
set_interface_property rst_in associatedClock wr_clk_in
set_interface_property rst_in synchronousEdges DEASSERT
set_interface_property rst_in ENABLED true
set_interface_property rst_in EXPORT_OF ""
set_interface_property rst_in PORT_NAME_MAP ""
set_interface_property rst_in CMSIS_SVD_VARIABLES ""
set_interface_property rst_in SVD_ADDRESS_GROUP ""

add_interface_port rst_in rst reset Input 1


# 
# connection point matrix_multiplier
# 
add_interface matrix_multiplier avalon end
set_interface_property matrix_multiplier addressUnits WORDS
set_interface_property matrix_multiplier associatedClock wr_clk_in
set_interface_property matrix_multiplier associatedReset rst_in
set_interface_property matrix_multiplier bitsPerSymbol 8
set_interface_property matrix_multiplier burstOnBurstBoundariesOnly false
set_interface_property matrix_multiplier burstcountUnits WORDS
set_interface_property matrix_multiplier explicitAddressSpan 0
set_interface_property matrix_multiplier holdTime 0
set_interface_property matrix_multiplier linewrapBursts false
set_interface_property matrix_multiplier maximumPendingReadTransactions 0
set_interface_property matrix_multiplier maximumPendingWriteTransactions 0
set_interface_property matrix_multiplier readLatency 0
set_interface_property matrix_multiplier readWaitStates 0
set_interface_property matrix_multiplier readWaitTime 0
set_interface_property matrix_multiplier setupTime 0
set_interface_property matrix_multiplier timingUnits Cycles
set_interface_property matrix_multiplier writeWaitTime 0
set_interface_property matrix_multiplier ENABLED true
set_interface_property matrix_multiplier EXPORT_OF ""
set_interface_property matrix_multiplier PORT_NAME_MAP ""
set_interface_property matrix_multiplier CMSIS_SVD_VARIABLES ""
set_interface_property matrix_multiplier SVD_ADDRESS_GROUP ""

add_interface_port matrix_multiplier address address Input "(macs_size+memory_size) - (0) + 1"
add_interface_port matrix_multiplier chipselect chipselect Input 1
add_interface_port matrix_multiplier writedata writedata Input data_size
add_interface_port matrix_multiplier readdata readdata Output data_size
add_interface_port matrix_multiplier write_en write Input 1
set_interface_assignment matrix_multiplier embeddedsw.configuration.isFlash 0
set_interface_assignment matrix_multiplier embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment matrix_multiplier embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment matrix_multiplier embeddedsw.configuration.isPrintableDevice 0

