#ifndef _ALTERA_HPS_SOC_SYSTEM_H_
#define _ALTERA_HPS_SOC_SYSTEM_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/home/juanfelipe/Documents/universidad/tesis/hardware/matrix_multiplier/hw/quartus/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'matrix_multiplier_avalon_0', class 'matrix_multiplier_avalon'
 * The macros are prefixed with 'MATRIX_MULTIPLIER_AVALON_0_'.
 * The prefix is the slave descriptor.
 */
#define MATRIX_MULTIPLIER_AVALON_0_COMPONENT_TYPE matrix_multiplier_avalon
#define MATRIX_MULTIPLIER_AVALON_0_COMPONENT_NAME matrix_multiplier_avalon_0
#define MATRIX_MULTIPLIER_AVALON_0_BASE 0x0
#define MATRIX_MULTIPLIER_AVALON_0_SPAN 131072
#define MATRIX_MULTIPLIER_AVALON_0_END 0x1ffff


#endif /* _ALTERA_HPS_SOC_SYSTEM_H_ */
